import Foundation

/// CPU-only zstd frame walker that classifies each inner zstd block's
/// literal section. Produces the go/no-go signal for Phase 1b — the GPU
/// Huffman literal decoder's target is `Compressed_4Stream` blocks; if
/// the corpus is mostly Raw / RLE / 1-stream / Treeless the kernel work
/// has too small a blast radius to be worth doing.
///
/// What this is and isn't:
///   * **Is** a header walker — reads the 1-byte frame-header descriptor,
///     optional window + dict-id + content-size fields, then the
///     3-byte block headers and 1-5-byte literals-section headers.
///     Skips block payloads entirely (zstd's compressed data) so it
///     stays cheap enough to call inside the parallel decode worker
///     without showing up in `parallel.decode` wall.
///   * **Isn't** a decoder. It doesn't validate Huffman trees, FSE
///     tables, or sequence sections. A malformed literals section
///     header is reported as `.unparseable` and the block is still
///     handed to libzstd unmodified — classification never gates or
///     mutates the decode path.
///
/// Reference: RFC 8478 (Zstandard Compression and the application/zstd
/// Media Type). Specifically:
///   * § 3.1.1.1  — Zstandard frames (magic + Frame_Header)
///   * § 3.1.1.2  — Frame_Header
///   * § 3.1.1.3.1 — Block_Header
///   * § 3.1.1.3.1.1 — Literals_Section_Header
///
/// Why hand-rolled vs. libzstd: `ZSTD_getFrameHeader` only exposes
/// frame-level metadata (window size, content size, dict ID). There is
/// no public API for per-block literal-header inspection. The hand
/// parse is ~150 LOC and the spec is unambiguous about every byte.
public enum ZstdLiteralClassifier {

    /// Six-bucket classification of one zstd inner block's literal
    /// section. Lifted to a per-`.knit`-block roll-up (byte-weighted
    /// majority) by callers that want a `.knit`-block-level number;
    /// for the Phase 1b gate the per-zstd-block view is what matters.
    public enum LiteralBucket: Sendable, CaseIterable {
        /// No literals section at all (Raw or RLE zstd block).
        case noLiterals
        /// Compressed_Block whose literals section is `Raw_Literals_Block`.
        case rawLiterals
        /// Compressed_Block whose literals section is `RLE_Literals_Block`.
        case rleLiterals
        /// Compressed_Block, single-stream Huffman. Phase 2 candidate.
        case compressed1Stream
        /// Compressed_Block, four-stream Huffman — **Phase 1b GPU target**.
        case compressed4Stream
        /// Treeless_Literals_Block (single or four streams). Reuses a
        /// Huffman tree transmitted by an earlier block in this frame.
        /// Out of Phase 1b scope (cross-block dependency complicates
        /// the threadgroup-per-block dispatch).
        case treeless
    }

    /// Per-bucket counts and total literal-section byte counts. Byte
    /// totals are over the **regenerated** literals (the decoded
    /// output size), not the compressed-on-disk size — that's what
    /// the GPU kernel would actually produce, and the right
    /// denominator for the "% bytes Huffman-4-stream" gate.
    public struct BlockTypeCounts: Sendable {
        public var counts: [LiteralBucket: Int]
        public var regeneratedBytes: [LiteralBucket: UInt64]

        public init() {
            counts = Dictionary(uniqueKeysWithValues:
                LiteralBucket.allCases.map { ($0, 0) })
            regeneratedBytes = Dictionary(uniqueKeysWithValues:
                LiteralBucket.allCases.map { ($0, 0) })
        }

        public mutating func add(_ b: LiteralBucket, regenerated: UInt64) {
            counts[b, default: 0] += 1
            regeneratedBytes[b, default: 0] += regenerated
        }

        public mutating func merge(_ other: BlockTypeCounts) {
            for b in LiteralBucket.allCases {
                counts[b, default: 0] += other.counts[b] ?? 0
                regeneratedBytes[b, default: 0] += other.regeneratedBytes[b] ?? 0
            }
        }

        public var totalBlocks: Int {
            counts.values.reduce(0, +)
        }
        public var totalRegeneratedBytes: UInt64 {
            regeneratedBytes.values.reduce(0, +)
        }
    }

    /// Roll-up describing one `.knit` block (which contains one zstd
    /// frame, which contains one or more zstd blocks). The per-zstd-block
    /// counts here can be merged across `.knit` blocks to produce the
    /// corpus-wide distribution.
    public struct KnitBlockClassification: Sendable {
        /// Per-zstd-block tally inside this `.knit` block.
        public let zstdBlockCounts: BlockTypeCounts
        /// Majority bucket by regenerated bytes — used for the
        /// `.knit`-block-level distribution row (informational).
        /// `.noLiterals` if the frame has no literals at all (all
        /// inner blocks Raw or RLE).
        public let dominantBucket: LiteralBucket
        /// True iff parsing terminated cleanly at the last block.
        /// False on any malformed input — callers add 1 to a separate
        /// "unparseable" counter and treat the partial counts as
        /// best-effort (still useful, just incomplete).
        public let fullyParsed: Bool
    }

    // MARK: - Entry point

    /// Classify every zstd block inside a single `.knit` block's
    /// compressed frame. Never throws — a malformed frame returns
    /// `fullyParsed: false` with whatever was parsed so far.
    public static func classify(frame: UnsafeBufferPointer<UInt8>) -> KnitBlockClassification {
        var counts = BlockTypeCounts()
        guard let base = frame.baseAddress else {
            return KnitBlockClassification(
                zstdBlockCounts: counts,
                dominantBucket: .noLiterals,
                fullyParsed: false
            )
        }
        var p = Pointer(base: base, end: base.advanced(by: frame.count))

        // 4-byte magic.
        guard let magic = p.readU32LE(), magic == 0xFD2F_B528 else {
            return KnitBlockClassification(
                zstdBlockCounts: counts,
                dominantBucket: .noLiterals,
                fullyParsed: false
            )
        }

        guard parseFrameHeader(&p) else {
            return KnitBlockClassification(
                zstdBlockCounts: counts,
                dominantBucket: .noLiterals,
                fullyParsed: false
            )
        }

        // Walk zstd blocks until we see one with Last_Block=1.
        while true {
            guard let bh = p.readU24LE() else {
                return KnitBlockClassification(
                    zstdBlockCounts: counts,
                    dominantBucket: counts.byteWeightedMajority(),
                    fullyParsed: false
                )
            }
            let isLast = (bh & 0x01) != 0
            let blockType = UInt8((bh >> 1) & 0x03)
            let blockSize = Int(bh >> 3)   // up to 21 bits

            switch blockType {
            case 0:  // Raw_Block — `blockSize` literal bytes follow.
                counts.add(.noLiterals, regenerated: UInt64(blockSize))
                if !p.skip(blockSize) {
                    return KnitBlockClassification(
                        zstdBlockCounts: counts,
                        dominantBucket: counts.byteWeightedMajority(),
                        fullyParsed: false
                    )
                }
            case 1:  // RLE_Block — 1-byte symbol, repeat `blockSize` times.
                counts.add(.noLiterals, regenerated: UInt64(blockSize))
                if !p.skip(1) {
                    return KnitBlockClassification(
                        zstdBlockCounts: counts,
                        dominantBucket: counts.byteWeightedMajority(),
                        fullyParsed: false
                    )
                }
            case 2:  // Compressed_Block — has a literals section.
                let blockStart = p
                guard let (bucket, regen) = readLiteralsSectionHeader(&p) else {
                    // Header malformed — skip the rest of the block
                    // payload (best-effort) and continue.
                    counts.add(.rawLiterals, regenerated: 0)  // treat as a
                                                              // placeholder
                                                              // so the
                                                              // total-block
                                                              // count is
                                                              // accurate
                    _ = blockStart  // keep `blockStart` referenced for clarity
                    if !p.skip(blockSize) {
                        return KnitBlockClassification(
                            zstdBlockCounts: counts,
                            dominantBucket: counts.byteWeightedMajority(),
                            fullyParsed: false
                        )
                    }
                    if isLast { break }
                    continue
                }
                counts.add(bucket, regenerated: regen)
                // Skip the remainder of the compressed block (we've
                // already advanced `p` by the literals header bytes).
                let bytesConsumed = blockStart.bytesUntil(p)
                let remaining = blockSize - bytesConsumed
                if remaining < 0 || !p.skip(remaining) {
                    return KnitBlockClassification(
                        zstdBlockCounts: counts,
                        dominantBucket: counts.byteWeightedMajority(),
                        fullyParsed: false
                    )
                }
            default:
                // Reserved (block_type == 3) → spec says decode must
                // fail. Stop and report best-effort.
                return KnitBlockClassification(
                    zstdBlockCounts: counts,
                    dominantBucket: counts.byteWeightedMajority(),
                    fullyParsed: false
                )
            }

            if isLast {
                return KnitBlockClassification(
                    zstdBlockCounts: counts,
                    dominantBucket: counts.byteWeightedMajority(),
                    fullyParsed: true
                )
            }
        }
    }

    // MARK: - Parsing helpers

    /// Skip past the variable-size Frame_Header section. Returns false
    /// on truncation.
    private static func parseFrameHeader(_ p: inout Pointer) -> Bool {
        guard let fhd = p.readU8() else { return false }
        let singleSegment = (fhd & 0x20) != 0
        let contentChecksum = (fhd & 0x04) != 0
        _ = contentChecksum  // we don't care; the trailing 4-byte
                             // checksum sits after the last block,
                             // outside this walker's scope
        let dictIDFlag = Int(fhd & 0x03)
        let fcsFlag = Int((fhd >> 6) & 0x03)

        // Window_Descriptor (1 byte) iff Single_Segment_flag == 0.
        if !singleSegment {
            if !p.skip(1) { return false }
        }

        // Dictionary_ID (0-4 bytes).
        let didSize: Int
        switch dictIDFlag {
        case 0: didSize = 0
        case 1: didSize = 1
        case 2: didSize = 2
        case 3: didSize = 4
        default: didSize = 0
        }
        if didSize > 0 {
            if !p.skip(didSize) { return false }
        }

        // Frame_Content_Size (0/1/2/4/8 bytes).
        let fcsSize: Int
        switch fcsFlag {
        case 0: fcsSize = singleSegment ? 1 : 0
        case 1: fcsSize = 2
        case 2: fcsSize = 4
        case 3: fcsSize = 8
        default: fcsSize = 0
        }
        if fcsSize > 0 {
            if !p.skip(fcsSize) { return false }
        }
        return true
    }

    /// Read the Literals_Section_Header at `p`. Advances `p` past the
    /// header bytes (1–5). Returns `(bucket, regenerated_size)` or nil
    /// on truncation / malformed header.
    private static func readLiteralsSectionHeader(_ p: inout Pointer) -> (LiteralBucket, UInt64)? {
        guard let b0 = p.readU8() else { return nil }
        let blockType = Int(b0 & 0x03)
        let sizeFormat = Int((b0 >> 2) & 0x03)

        switch blockType {
        case 0, 1:  // Raw / RLE
            // Size_Format encodes regenerated_size width:
            //   00 / 10  → 5-bit  regen (header 1 byte)
            //   01       → 12-bit regen (header 2 bytes)
            //   11       → 20-bit regen (header 3 bytes)
            let bucket: LiteralBucket = (blockType == 0) ? .rawLiterals : .rleLiterals
            switch sizeFormat & 0x03 {
            case 0, 2:
                let regen = UInt64(b0 >> 3)
                // For RLE the *symbol* byte follows the header.
                if blockType == 1 {
                    if !p.skip(1) { return nil }
                }
                return (bucket, regen)
            case 1:
                guard let b1 = p.readU8() else { return nil }
                let regen = (UInt64(b0) >> 4) | (UInt64(b1) << 4)
                if blockType == 1 {
                    if !p.skip(1) { return nil }
                }
                return (bucket, regen & 0xFFF)
            case 3:
                guard let b1 = p.readU8(), let b2 = p.readU8() else { return nil }
                let regen = (UInt64(b0) >> 4)
                    | (UInt64(b1) << 4)
                    | (UInt64(b2) << 12)
                if blockType == 1 {
                    if !p.skip(1) { return nil }
                }
                return (bucket, regen & 0xFFFFF)
            default:
                return nil
            }
        case 2, 3:  // Compressed / Treeless
            // Per RFC 8478 § 3.1.1.3.1.1:
            //   sizeFormat 0 → 1 stream,  3-byte header, 10-bit regen + 10-bit compressed
            //   sizeFormat 1 → 4 streams, 3-byte header, 10-bit regen + 10-bit compressed
            //   sizeFormat 2 → 4 streams, 4-byte header, 14-bit regen + 14-bit compressed
            //   sizeFormat 3 → 4 streams, 5-byte header, 18-bit regen + 18-bit compressed
            //
            // We only care about the regen for byte-weighted majority.
            // Treeless reuses an earlier Huffman tree; it's still out
            // of Phase 1b scope, but the parse is identical.
            let regen: UInt64
            switch sizeFormat {
            case 0, 1:
                guard let b1 = p.readU8(), let b2 = p.readU8() else { return nil }
                let _ = b2  // compressed_size; not needed for the gate
                regen = (UInt64(b0) >> 4) | (UInt64(b1) << 4)
                let regen10 = regen & 0x3FF  // 10 bits
                let bucket: LiteralBucket
                if blockType == 3 {
                    bucket = .treeless
                } else if sizeFormat == 0 {
                    bucket = .compressed1Stream
                } else {
                    bucket = .compressed4Stream
                }
                return (bucket, regen10)
            case 2:
                guard let b1 = p.readU8(),
                      let b2 = p.readU8(),
                      let b3 = p.readU8() else { return nil }
                let _ = b3
                let r = (UInt64(b0) >> 4) | (UInt64(b1) << 4) | (UInt64(b2) << 12)
                let regen14 = r & 0x3FFF  // 14 bits
                let bucket: LiteralBucket = (blockType == 3) ? .treeless : .compressed4Stream
                return (bucket, regen14)
            case 3:
                guard let b1 = p.readU8(),
                      let b2 = p.readU8(),
                      let b3 = p.readU8(),
                      let b4 = p.readU8() else { return nil }
                let _ = b4
                let r = (UInt64(b0) >> 4)
                    | (UInt64(b1) << 4)
                    | (UInt64(b2) << 12)
                    | (UInt64(b3) << 20)
                let regen18 = r & 0x3_FFFF  // 18 bits
                let bucket: LiteralBucket = (blockType == 3) ? .treeless : .compressed4Stream
                return (bucket, regen18)
            default:
                return nil
            }
        default:
            return nil
        }
    }
}

extension ZstdLiteralClassifier.BlockTypeCounts {
    /// Pick the bucket with the most regenerated bytes — used as the
    /// `.knit`-block-level "dominant" classification.
    fileprivate func byteWeightedMajority() -> ZstdLiteralClassifier.LiteralBucket {
        var winner: ZstdLiteralClassifier.LiteralBucket = .noLiterals
        var maxBytes: UInt64 = 0
        for b in ZstdLiteralClassifier.LiteralBucket.allCases {
            let n = regeneratedBytes[b] ?? 0
            if n > maxBytes {
                maxBytes = n
                winner = b
            }
        }
        return winner
    }
}

// MARK: - Pointer helper

/// Lightweight bounded pointer over `frame.baseAddress..<end`. Returns
/// nil from `readU*` / `skip` on overrun rather than crashing; the
/// classifier turns any nil into a `fullyParsed: false` result.
private struct Pointer {
    var base: UnsafePointer<UInt8>
    let end: UnsafePointer<UInt8>

    init(base: UnsafePointer<UInt8>, end: UnsafePointer<UInt8>) {
        self.base = base
        self.end = end
    }

    var remaining: Int { end - base }

    mutating func readU8() -> UInt8? {
        guard remaining >= 1 else { return nil }
        let v = base.pointee
        base = base.advanced(by: 1)
        return v
    }

    mutating func readU24LE() -> UInt32? {
        guard remaining >= 3 else { return nil }
        let b0 = UInt32(base.pointee)
        let b1 = UInt32(base.advanced(by: 1).pointee)
        let b2 = UInt32(base.advanced(by: 2).pointee)
        base = base.advanced(by: 3)
        return b0 | (b1 << 8) | (b2 << 16)
    }

    mutating func readU32LE() -> UInt32? {
        guard remaining >= 4 else { return nil }
        let b0 = UInt32(base.pointee)
        let b1 = UInt32(base.advanced(by: 1).pointee)
        let b2 = UInt32(base.advanced(by: 2).pointee)
        let b3 = UInt32(base.advanced(by: 3).pointee)
        base = base.advanced(by: 4)
        return b0 | (b1 << 8) | (b2 << 16) | (b3 << 24)
    }

    mutating func skip(_ n: Int) -> Bool {
        guard n >= 0, remaining >= n else { return false }
        base = base.advanced(by: n)
        return true
    }

    /// Number of bytes the cursor moved between `self` (the snapshot)
    /// and `current` (after some reads on a value-typed copy). Used
    /// to compute how many bytes the literals-header parse consumed
    /// so the caller can advance past the rest of the compressed
    /// block payload.
    func bytesUntil(_ current: Pointer) -> Int {
        return current.base - self.base
    }
}
