import Foundation

/// Accumulator for the Phase 1b.0 spike's zstd literal-section
/// classifier output. Sibling to `StageAnalytics` — same sharded-NSLock
/// pattern (32 shards via the high bits of a Knuth multiplicative hash
/// keyed on `Thread.current`'s `ObjectIdentifier`) so per-block
/// `record()` from inside `HybridZstdBatchDecoder`'s parallel decode
/// worker is not a contention point. Without sharding the single
/// NSLock would inflate the very `parallel.decode` measurement we're
/// trying to gate on (the post-PR-#34/#35 lesson — see
/// `StageAnalytics`'s long doc-block).
///
/// What it records:
///   * One row per `.knit` block (`recordKnitBlock`) — the byte-weighted
///     dominant bucket for that block.
///   * One zstd-block-counts struct per `.knit` block, accumulated into
///     a corpus-wide `BlockTypeCounts` (`recordKnitBlock` adds them).
///   * Plus an `unparseable` counter for `.knit` blocks where the
///     header walk hit a truncation / malformed input. These still
///     count as one `.knit` block toward the total — the partial
///     bucket counts they contributed are kept (best-effort).
///
/// What it does **not** do:
///   * Mutate or gate the decode path. The classifier never throws and
///     the accumulator is pure-write from the worker's perspective.
///   * Carry wall-clock — the classifier's CPU cost is small enough
///     that we'd want a separate stage in `StageAnalytics` only if
///     `parallel.decode` regressed visibly after wiring it in.
///
/// `@unchecked Sendable`: the safety property (per-shard NSLock around
/// every mutation; snapshot locks every shard in index order) is
/// enforced by the locks, not the type system — same `CLAUDE.md`
/// Rule 1.3 pattern `StageAnalytics` uses.
public final class LiteralTypeAnalytics: @unchecked Sendable {

    public struct Snapshot: Sendable {
        /// Distribution at zstd-block granularity (one row per inner
        /// zstd block, accumulated across every `.knit` block). The
        /// Phase 1b gate is `Compressed_4Stream` byte share of this
        /// distribution.
        public let zstdBlockCounts: ZstdLiteralClassifier.BlockTypeCounts
        /// Distribution at `.knit`-block granularity (one row per
        /// `.knit` block, bucketed by the byte-weighted dominant
        /// classification). Informational — useful for telling apart
        /// "uniform 4-stream throughout" from "4-stream majority but
        /// with treeless-tree blocks interleaved".
        public let knitBlockCounts: ZstdLiteralClassifier.BlockTypeCounts
        public let unparseableKnitBlocks: Int
        public let totalKnitBlocksSeen: Int
    }

    /// One shard's mutable state. The doc-block on `StageAnalytics`
    /// explains why per-shard NSLocks beat a single contended lock.
    private final class Shard {
        let lock = NSLock()
        var zstdBlockCounts = ZstdLiteralClassifier.BlockTypeCounts()
        var knitBlockCounts = ZstdLiteralClassifier.BlockTypeCounts()
        var unparseable: Int = 0
        var total: Int = 0
    }

    private static let shardBits = 5
    private static let shardCount = 1 << shardBits   // 32

    private let shards: [Shard]

    public init() {
        self.shards = (0..<Self.shardCount).map { _ in Shard() }
    }

    /// Record one `.knit` block's classification result. Called from
    /// inside `parallelDecodeBlocks` worker, **before** the libzstd
    /// decode call, so the classifier work overlaps decode in time —
    /// not stacked on top of it.
    public func recordKnitBlock(_ c: ZstdLiteralClassifier.KnitBlockClassification) {
        let shard = currentShard()
        shard.lock.lock()
        shard.zstdBlockCounts.merge(c.zstdBlockCounts)
        // The `.knit`-block-level row counts the dominant bucket once
        // with the total regenerated bytes attributed to that bucket.
        // Total bytes = sum across this `.knit` block's zstd blocks.
        let totalRegen = c.zstdBlockCounts.totalRegeneratedBytes
        shard.knitBlockCounts.add(c.dominantBucket, regenerated: totalRegen)
        if !c.fullyParsed { shard.unparseable += 1 }
        shard.total += 1
        shard.lock.unlock()
    }

    public func snapshot() -> Snapshot {
        for shard in shards { shard.lock.lock() }
        defer {
            for shard in shards { shard.lock.unlock() }
        }
        var zstd = ZstdLiteralClassifier.BlockTypeCounts()
        var knit = ZstdLiteralClassifier.BlockTypeCounts()
        var unparseable = 0
        var total = 0
        for shard in shards {
            zstd.merge(shard.zstdBlockCounts)
            knit.merge(shard.knitBlockCounts)
            unparseable += shard.unparseable
            total += shard.total
        }
        return Snapshot(
            zstdBlockCounts: zstd,
            knitBlockCounts: knit,
            unparseableKnitBlocks: unparseable,
            totalKnitBlocksSeen: total
        )
    }

    /// Same high-bits-of-Knuth pattern as `StageAnalytics.currentShard()`.
    /// Verbatim because the rationale is identical (pointer-derived
    /// hashes share low bits across sibling thread allocations, so
    /// using `& mask` would collapse 16 workers onto 1-2 shards).
    private func currentShard() -> Shard {
        let raw = UInt(bitPattern: ObjectIdentifier(Thread.current).hashValue)
        let idx = Int((raw &* 11400714819323198485) >> (UInt.bitWidth - Self.shardBits))
        return shards[idx]
    }
}
