import XCTest
import Foundation
@testable import KnitCore

/// Unit tests for the Phase 1b.0 spike's zstd literal-section
/// classifier. The classifier walks zstd frame + block + literals
/// section headers only — no payloads — so its correctness is a
/// pure-bit-parse property, exercised here by feeding it real zstd
/// frames produced by libzstd at various compression levels and
/// asserting:
///
///   * Every well-formed frame is `fullyParsed: true`.
///   * Total regenerated byte count across all classified zstd
///     blocks equals the frame's original uncompressed size.
///   * Compressing repeating text yields at least one
///     `Compressed_4Stream` (or `Compressed_1Stream`, for tiny inputs)
///     block — the classifier's primary discrimination target.
///   * Compressing pure-random bytes yields predominantly `Raw_Literals`
///     or `noLiterals` blocks (random doesn't Huffman well, libzstd
///     stores it as raw).
///   * A truncated frame returns `fullyParsed: false` without
///     crashing.
final class ZstdLiteralClassifierTests: XCTestCase {

    /// Round-trip helper: compress `input` at `level`, hand the frame
    /// to the classifier, return the result.
    private func classify(_ input: Data, level: Int32) throws -> ZstdLiteralClassifier.KnitBlockClassification {
        let backend = CPUZstd()
        let frame = try input.withUnsafeBytes { (raw: UnsafeRawBufferPointer) -> Data in
            let typed = raw.bindMemory(to: UInt8.self)
            return try backend.compressBlock(typed, level: level)
        }
        return frame.withUnsafeBytes { (raw: UnsafeRawBufferPointer) in
            let typed = raw.bindMemory(to: UInt8.self)
            return ZstdLiteralClassifier.classify(frame: typed)
        }
    }

    /// Tiny repeating-text input at level 3: usually yields a
    /// `Compressed_Block` with `Compressed_1Stream` literals (small
    /// inputs); the literal section contains the unique-byte alphabet
    /// and the sequences section expands it back to the full output.
    /// Important property: the classifier's `totalRegeneratedBytes`
    /// is the *literal-section* regenerated size, **not** the total
    /// zstd-block output — sequences are out of scope for Phase 1b.
    func testCompressibleTextClassifiesCleanly() throws {
        let unit = "Knit Phase 1b.0 classifier sanity input. " as String
        var s = ""
        while s.utf8.count < 16 * 1024 {
            s += unit
        }
        let input = Data(s.utf8)

        let c = try classify(input, level: 3)

        XCTAssertTrue(c.fullyParsed,
                      "well-formed zstd frame must classify cleanly")
        XCTAssertGreaterThan(c.zstdBlockCounts.totalBlocks, 0,
                             "must see at least one zstd block")
        // Literal section regen must fit inside the original input
        // bytes (sequences only ever copy, never produce more
        // literals than the input contained). Allows < and == both.
        XCTAssertLessThanOrEqual(c.zstdBlockCounts.totalRegeneratedBytes,
                                 UInt64(input.count),
                                 "literal-section regen cannot exceed input size")
    }

    /// Pure random bytes at level 3: libzstd typically stores these
    /// as `Raw_Block` (no literals section) or `Compressed_Block`
    /// with `Raw_Literals_Block` (Huffman doesn't help). Either way
    /// the classifier must parse cleanly and a noLiterals row's
    /// regen must equal that block's raw size (for Raw_Block we add
    /// `blockSize` as the regen since the raw bytes *are* the
    /// output).
    func testIncompressibleClassifiesCleanly() throws {
        var rng = SystemRandomNumberGenerator()
        var bytes = [UInt8](repeating: 0, count: 8 * 1024)
        for i in 0..<bytes.count {
            bytes[i] = UInt8.random(in: 0...255, using: &rng)
        }
        let input = Data(bytes)

        let c = try classify(input, level: 3)

        XCTAssertTrue(c.fullyParsed,
                      "well-formed random-bytes frame must classify cleanly")
        XCTAssertGreaterThan(c.zstdBlockCounts.totalBlocks, 0)
        XCTAssertEqual(c.zstdBlockCounts.counts[.treeless] ?? 0, 0,
                       "incompressible random input never reuses a prior Huffman tree")
    }

    /// Truncated frame: classifier must report `fullyParsed: false`
    /// without crashing. Truncate after the first block header so the
    /// parse aborts mid-block.
    func testTruncatedFrameReportsUnparseable() throws {
        let backend = CPUZstd()
        let s = String(repeating: "abcabc", count: 4096)
        let input = Data(s.utf8)
        let frame = try input.withUnsafeBytes { (raw: UnsafeRawBufferPointer) -> Data in
            let typed = raw.bindMemory(to: UInt8.self)
            return try backend.compressBlock(typed, level: 3)
        }
        // Keep just the magic + frame header + first 4 bytes — far
        // shorter than any real complete block payload.
        let truncated = frame.prefix(min(15, frame.count))
        let c = truncated.withUnsafeBytes { (raw: UnsafeRawBufferPointer) in
            let typed = raw.bindMemory(to: UInt8.self)
            return ZstdLiteralClassifier.classify(frame: typed)
        }
        XCTAssertFalse(c.fullyParsed,
                       "truncated frame must report fullyParsed=false")
        // Must not crash — the no-crash property is asserted by the
        // test reaching this line.
    }

    /// Bad magic number: classifier returns immediately with
    /// `fullyParsed: false` and zero counts.
    func testBadMagicReportsUnparseable() throws {
        // 16 bytes of zeros — magic check sees 0x00000000, not 0xFD2FB528.
        let bytes = [UInt8](repeating: 0, count: 16)
        let c = bytes.withUnsafeBufferPointer { typed in
            ZstdLiteralClassifier.classify(frame: typed)
        }
        XCTAssertFalse(c.fullyParsed)
        XCTAssertEqual(c.zstdBlockCounts.totalBlocks, 0)
    }

    /// Larger input designed to span multiple zstd inner blocks (which
    /// the spec caps at 128 KiB regenerated bytes each). 512 KiB of
    /// pseudo-random-but-structured data should produce at least 4
    /// inner blocks, exercising the block-walk loop.
    func testMultiBlockFrameClassifiesEveryBlock() throws {
        var d = Data(capacity: 512 * 1024)
        var s: UInt64 = 0xCAFEBABE
        for _ in 0..<(512 * 1024 / 8) {
            // Mix repeating + pseudo-random to encourage libzstd to
            // emit varied literal block types.
            s = s &* 6364136223846793005 &+ 1442695040888963407
            withUnsafeBytes(of: s.littleEndian) { raw in
                d.append(contentsOf: raw)
            }
        }
        let c = try classify(d, level: 3)

        XCTAssertTrue(c.fullyParsed)
        XCTAssertGreaterThanOrEqual(c.zstdBlockCounts.totalBlocks, 4,
                                    "512 KiB input must produce ≥ 4 zstd inner blocks (spec cap is 128 KiB regen per block)")
        // Literal-section regen sum is bounded by total output (the
        // sequences copy from earlier output, never inflate beyond
        // the original).
        XCTAssertLessThanOrEqual(c.zstdBlockCounts.totalRegeneratedBytes,
                                 UInt64(d.count),
                                 "literal-section regen cannot exceed total input")
    }
}
