import Foundation

/// Top-level extractor for `.knit` archives.
///
/// Sits between the CLI and `KnitReader`: opens the archive, validates
/// each entry name with `SafePath` (zip-slip defence), and routes large
/// entries through the optional GPU CRC32 verifier. Decompression itself
/// happens inside `KnitReader.extract`, driven by `HybridZstdBatchDecoder`
/// which parallelises per-block libzstd calls across worker threads.
///
/// Mixed-granularity parallelism (mirrors `KnitCompressor` / PR #27):
///
///   * **Large entries** (≥ 16 MiB — enough blocks to saturate the
///     worker pool on their own) take a **serial-across-entries
///     path** with intra-entry block-level parallelism inside the
///     decoder. Memory stays bounded for 100 GB+ single files.
///   * **Small entries** (the typical "git tree with 100 k tiny files"
///     workload) are gathered into batches and extracted **across
///     workers in parallel** via `concurrentMap`. Each worker opens
///     its own `FileHandle`, decodes its entry, and runs CRC verify
///     end-to-end — no archive-write order to preserve since each
///     entry has its own output URL.
///
/// This split solved the bottleneck the unpack `--analyze` data
/// flagged on the github corpus: ~32 s of "unaccounted" wall (per-entry
/// `createDirectory` + `createFile` + `FileHandle` open + decode +
/// `synchronize` + `verifyCRC` × 100 k entries) processed serially
/// left 15 of 16 cores idle, capping unpack throughput at ~250 MB/s
/// on a 9 GB / 100 k-entry corpus. With cross-entry batching we get
/// the same N-way parallelism the unpack path already had on big
/// files, just lifted up to entry granularity.
public final class KnitExtractor {

    /// Aggregate result returned to the CLI / callers. `gpuVerifyUsed`
    /// lets the CLI report which verification path actually ran for the
    /// archive (the GPU path is conditional on entry size and Metal
    /// availability).
    public struct Stats: Sendable {
        public let entries: Int
        public let bytesOut: UInt64
        public let elapsed: TimeInterval
        /// True iff at least one entry was verified on the GPU.
        public let gpuVerifyUsed: Bool
    }

    /// When true, large entries are CRC-verified on the GPU after extraction.
    /// On unified-memory Apple Silicon the verification mmap is page-cache
    /// hot so the cost is dominated by the GPU dispatch + compute, not I/O.
    public var useGPUVerify: Bool

    /// PR #75. When true (the default), each extracted entry is
    /// re-read from disk after the write completes and its CRC32 is
    /// recomputed against the archive's stored CRC. This is
    /// belt-and-braces defence-in-depth on top of the decode-side
    /// CRC (`HybridZstdBatchDecoder.decode → expectedCRC32`), which
    /// already catches every bug class except "disk lost bytes after
    /// my write(2) returned". On APFS + modern NVMe the latter is
    /// effectively impossible (the filesystem block-checksums
    /// independently), so the cost — ~60 s of wall on the user's
    /// 80 GB .pvm.knit, dominating total unpack time at 88 s — is
    /// pure paranoia tax.
    ///
    /// Setting this to `false` skips the post-write re-read pass
    /// entirely. Decode-side verification still runs on every
    /// batch, so silent decode bugs / memory corruption still
    /// throw. The CLI exposes this as `--no-post-verify`.
    public var postWriteVerify: Bool

    /// Optional progress sink. Receives one `advance(by:)` call per
    /// decompressed block, plus a final per-entry catch-up so the line
    /// reaches 100% even when the verify path runs.
    public var progressReporter: ProgressReporter?

    /// Number of worker threads. Used both for cross-entry parallelism
    /// (this orchestrator's `concurrentMap`) and intra-entry block
    /// parallelism (the staged decoder's own `concurrentMap`). Defaults
    /// to `activeProcessorCount`; pass 1 to force fully serial extract
    /// (mostly useful in tests).
    public var concurrency: Int

    /// Optional per-stage timing accumulator. Wired through to the
    /// staged decoder; nil = no instrumentation overhead. Driven by
    /// the CLI's hidden `--analyze` flag, which renders the snapshot
    /// after extract finishes.
    public var analytics: StageAnalytics?

    /// Phase 1b.0 spike accumulator for the zstd literal-section
    /// classifier. Sibling to `analytics`; nil = no overhead. When
    /// supplied alongside `analytics` (i.e. `--analyze` is set), every
    /// `.knit` block's zstd frame is walked by
    /// `ZstdLiteralClassifier` inside the parallel decode worker, and
    /// the distribution is rendered to stderr after the usual stage
    /// table. The result tells us whether Phase 1b's GPU Huffman
    /// kernel work has enough blast radius on this corpus to be worth
    /// building (≥ 70 % `Compressed_4Stream` by regenerated bytes).
    public var literalTypeAnalytics: LiteralTypeAnalytics?

    public init(useGPUVerify: Bool = true,
                postWriteVerify: Bool = true,
                progressReporter: ProgressReporter? = nil,
                concurrency: Int = ProcessInfo.processInfo.activeProcessorCount,
                analytics: StageAnalytics? = nil,
                literalTypeAnalytics: LiteralTypeAnalytics? = nil) {
        self.useGPUVerify = useGPUVerify
        self.postWriteVerify = postWriteVerify
        self.progressReporter = progressReporter
        self.concurrency = max(1, concurrency)
        self.analytics = analytics
        self.literalTypeAnalytics = literalTypeAnalytics
    }

    /// Threshold above which an entry takes the serial-across-entries
    /// path. Below this size, intra-entry block parallelism gains
    /// little (entries this small typically have 1-2 blocks) and
    /// cross-entry parallelism is the only lever.
    private static let largeEntryThreshold: UInt64 = 16 * 1024 * 1024

    public func extract(archive: URL, to destDir: URL) throws -> Stats {
        let reader = try KnitReader(url: archive)
        try FileManager.default.createDirectory(at: destDir, withIntermediateDirectories: true)

        // Lazily instantiate the GPU CRC pipeline. Failing to construct one
        // (no Metal device, kernel compile failure, etc.) silently falls
        // back to libdeflate's CPU CRC32 — verification still happens.
        let gpuCRC: MetalCRC32? = useGPUVerify ? MetalCRC32() : nil
        var gpuUsed = false

        let entries = reader.archive.entries

        // PR #82: compute every entry's destination path as a
        // byte-preserving String via `POSIXFile.joinPath`. URL-based
        // composition (`destDir.appendingPathComponent(name).path`)
        // applies macOS Foundation's NFD canonical-decomposition
        // normalization to path strings, silently rewriting
        // non-ASCII filenames (e.g. Japanese `プ` U+30D7 → `フ゜`
        // U+30D5 + U+309A) so the unpacked tree no longer
        // byte-matches the input. See `POSIXFile.swift` header for
        // the full analysis.
        let destDirPath = destDir.path

        // Pre-create every parent directory in a single serial pass
        // before kicking off the parallel-extract phase. Without this,
        // 16 workers concurrently call `mkdir(2)` on the same parent
        // inodes — APFS serialises on the parent's b-tree lock, so
        // concurrent calls effectively queue inside the kernel. On a
        // 100 k-entry github tree where many entries share a parent
        // (`node_modules/foo/...`), the contention dominated the
        // parallel-extract win and produced a wall-time *regression*
        // relative to the serial path the PR #31 work replaced.
        // Doing the dir creates up front is O(distinct parents) and
        // runs single-threaded so APFS sees a clean queue depth of
        // 1 — fast and contention-free. The per-entry mkdir-safety-net
        // calls inside `KnitReader.extract` then become cheap
        // already-exists no-ops.
        var parentPaths: Set<String> = []
        // Each entry's outPath is the byte-preserving destination
        // path; we cache it in the parent-path build pass and reuse
        // below in the extract loop so the SafePath validation +
        // string join is paid once per entry.
        var perEntryOutPaths: [String] = []
        perEntryOutPaths.reserveCapacity(entries.count)
        for entry in entries {
            let outPath = try SafePath.resolvePath(name: entry.name,
                                                    into: destDirPath)
            perEntryOutPaths.append(outPath)
            if entry.isDirectory {
                parentPaths.insert(outPath)
            }
            if let slash = outPath.lastIndex(of: "/") {
                parentPaths.insert(String(outPath[..<slash]))
            }
        }
        for parentPath in parentPaths {
            // Best-effort: any individual create failure (e.g. EEXIST
            // race with the user touching the tree mid-extract) is
            // ignored here and re-attempted lazily inside
            // `KnitReader.extract`. We only care about the bulk-of-the-
            // tree case where pre-creating eliminates contention.
            // `POSIXFile.mkdirParents` uses raw `mkdir(2)` with
            // `withCString` so the segment's UTF-8 bytes flow
            // verbatim to the kernel — no NFD round-trip via
            // Foundation. PR #82.
            _ = POSIXFile.mkdirParents(parentPath)
        }
        let start = ContinuousClock.now
        var bytesOut: UInt64 = 0

        // Capture values for the @Sendable closure without pulling
        // `self` in. Each parallel worker uses its own decoder
        // instance because `HybridZstdBatchDecoder` carries
        // per-entry mutable state (watchdog poisoning + slow-batch
        // counters) that would race if shared across concurrent
        // `decode` calls.
        let analyticsLocal = analytics
        let literalTypeAnalyticsLocal = literalTypeAnalytics
        let reporter = progressReporter
        let gpuCRCLocal = gpuCRC
        let readerLocal = reader
        // PR #75: capture the flag for the @Sendable closure below.
        let postWriteVerifyLocal = postWriteVerify
        // PR #82: `destDirLocal` removed — destination paths are
        // now precomputed into `perEntryOutPaths` so the closure
        // doesn't need to recompose them per entry.
        // Inner-decoder concurrency = 1 in the parallel-batch path:
        // outer entry-level parallelism already saturates the worker
        // pool, and nested 16-way × 16-way `concurrentMap` would just
        // queue 256 tasks on GCD. Large-entry serial path uses
        // `self.concurrency` for intra-entry block parallelism.
        let innerConcurrency = 1
        let outerConcurrency = self.concurrency

        // For the serial path, share one decoder across consecutive
        // large entries (its per-entry state resets at the top of
        // `decode`). Cheap to hold across the whole loop.
        let serialDecoder = HybridZstdBatchDecoder(
            concurrency: outerConcurrency,
            analytics: analytics,
            literalTypeAnalytics: literalTypeAnalytics
        )

        var i = 0
        while i < entries.count {
            let entry = entries[i]

            // Large entry: serial across entries, parallel within.
            if entry.uncompressedSize >= Self.largeEntryThreshold {
                // Reuse the byte-preserving path computed in the
                // pre-create pass above. PR #82.
                let outPath = perEntryOutPaths[i]
                try reader.extract(
                    entry,
                    toPath: outPath,
                    gpuCRC: gpuCRC,
                    progressReporter: progressReporter,
                    stagedDecoder: serialDecoder,
                    postWriteVerify: postWriteVerify
                )
                bytesOut += entry.uncompressedSize
                if gpuCRC != nil, entry.uncompressedSize >= 4 * 1024 * 1024 {
                    gpuUsed = true
                }
                i += 1
                continue
            }

            // Run of small entries: gather a batch and decompress in
            // parallel. There's no archive-write ordering to preserve
            // (unlike pack) — each entry has its own output URL.
            var j = i
            let maxBatch = max(outerConcurrency * 4, 8)
            while j < entries.count
                && (j - i) < maxBatch
                && entries[j].uncompressedSize < Self.largeEntryThreshold {
                j += 1
            }
            let batch = Array(entries[i..<j])

            // Capture the relevant slice of byte-preserving paths.
            // Per-entry outPath is indexed by absolute entry index `k`,
            // computed in the pre-create pass above. PR #82.
            let batchOutPaths = Array(perEntryOutPaths[i..<j])
            let _: [UInt64] = try concurrentMap(
                Array(batch.indices),
                concurrency: outerConcurrency
            ) { k in
                let entry = batch[k]
                let outPath = batchOutPaths[k]
                // Per-worker decoder: cheap to construct (just stores
                // refs), avoids racing on shared
                // `consecutiveSlowBatches` / `poisonedThisEntry` state.
                let perWorkerDecoder = HybridZstdBatchDecoder(
                    concurrency: innerConcurrency,
                    analytics: analyticsLocal,
                    literalTypeAnalytics: literalTypeAnalyticsLocal
                )
                try readerLocal.extract(
                    entry,
                    toPath: outPath,
                    gpuCRC: gpuCRCLocal,
                    progressReporter: reporter,
                    stagedDecoder: perWorkerDecoder,
                    postWriteVerify: postWriteVerifyLocal
                )
                return entry.uncompressedSize
            }

            for entry in batch {
                bytesOut += entry.uncompressedSize
                if gpuCRC != nil, entry.uncompressedSize >= 4 * 1024 * 1024 {
                    gpuUsed = true
                }
            }
            i = j
        }

        let elapsed = ContinuousClock.now - start
        return Stats(
            entries: entries.count,
            bytesOut: bytesOut,
            elapsed: elapsed.timeIntervalSeconds,
            gpuVerifyUsed: gpuUsed
        )
    }
}
